<a href="https://colab.research.google.com/github/JordanJaner/deep_learning_challenge/blob/main/Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [ ]:
url = 'Resources/charity_data.csv'

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv(url)
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN', 'NAME'])

In [ ]:
# Determine the number of unique values in each column.
for x in application_df.columns:
    print(x, len(application_df[x].unique()))

APPLICATION_TYPE 17
AFFILIATION 6
CLASSIFICATION 71
USE_CASE 5
ORGANIZATION 4
STATUS 2
INCOME_AMT 9
SPECIAL_CONSIDERATIONS 2
ASK_AMT 8747
IS_SUCCESSFUL 2

In [ ]:
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
counts = application_df['APPLICATION_TYPE'].value_counts()
counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(counts[counts<500].index)
application_types_to_replace

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
countsbinning = application_df['CLASSIFICATION'].value_counts()

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
countsclassification = countsbinning[countsbinning>1]
countsclassification

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list (countsbinning[countsbinning<100].index)
classifications_to_replace

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values
y

# Take out IS_SUCCESSFUL
X = application_df.drop('IS_SUCCESSFUL', axis=1).values
X

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=7
hidden_nodes_layer2=14
hidden_nodes_layer3=21

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 7)                 350

 dense_1 (Dense)             (None, 14)                112

 dense_2 (Dense)             (None, 1)                 15

=================================================================
Total params: 477
Trainable params: 477
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [ ]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
684/684 [==============================] - 3s 4ms/step - loss: 0.6111 - accuracy: 0.6760 - val_loss: 0.5588 - val_accuracy: 0.7295
Epoch 2/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5638 - accuracy: 0.7218 - val_loss: 0.5499 - val_accuracy: 0.7352
Epoch 3/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5579 - accuracy: 0.7245 - val_loss: 0.5484 - val_accuracy: 0.7370
Epoch 4/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5557 - accuracy: 0.7278 - val_loss: 0.5483 - val_accuracy: 0.7357
Epoch 5/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5540 - accuracy: 0.7297 - val_loss: 0.5489 - val_accuracy: 0.7383
Epoch 6/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5529 - accuracy: 0.7299 - val_loss: 0.5470 - val_accuracy: 0.7378
Epoch 7/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5522 - accuracy: 0.7293 - val_loss: 0.5463 - val_accuracy: 0.7370
Epoch 8/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5512 - accuracy: 0.7314 - val_loss: 0.5449 - val_accuracy: 0.7370
Epoch 9/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5506 - accuracy: 0.7310 - val_loss: 0.5457 - val_accuracy: 0.7385
Epoch 10/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5499 - accuracy: 0.7320 - val_loss: 0.5448 - val_accuracy: 0.7370
Epoch 11/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5498 - accuracy: 0.7314 - val_loss: 0.5449 - val_accuracy: 0.7385
Epoch 12/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7311 - val_loss: 0.5449 - val_accuracy: 0.7365
Epoch 13/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7323 - val_loss: 0.5444 - val_accuracy: 0.7388
Epoch 14/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5482 - accuracy: 0.7319 - val_loss: 0.5450 - val_accuracy: 0.7367
Epoch 15/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5482 - accuracy: 0.7308 - val_loss: 0.5421 - val_accuracy: 0.7396
Epoch 16/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7320 - val_loss: 0.5416 - val_accuracy: 0.7385
Epoch 17/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5473 - accuracy: 0.7314 - val_loss: 0.5423 - val_accuracy: 0.7385
Epoch 18/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5470 - accuracy: 0.7322 - val_loss: 0.5437 - val_accuracy: 0.7378
Epoch 19/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7316 - val_loss: 0.5455 - val_accuracy: 0.7383
Epoch 20/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7331 - val_loss: 0.5461 - val_accuracy: 0.7385
Epoch 21/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5464 - accuracy: 0.7321 - val_loss: 0.5431 - val_accuracy: 0.7378
Epoch 22/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5460 - accuracy: 0.7319 - val_loss: 0.5447 - val_accuracy: 0.7370
Epoch 23/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5460 - accuracy: 0.7319 - val_loss: 0.5435 - val_accuracy: 0.7388
Epoch 24/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5458 - accuracy: 0.7318 - val_loss: 0.5420 - val_accuracy: 0.7380
Epoch 25/100
684/684 [==============================] - 3s 5ms/step - loss: 0.5456 - accuracy: 0.7320 - val_loss: 0.5424 - val_accuracy: 0.7383
Epoch 26/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7335 - val_loss: 0.5415 - val_accuracy: 0.7393
Epoch 27/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7327 - val_loss: 0.5441 - val_accuracy: 0.7378
Epoch 28/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5451 - accuracy: 0.7324 - val_loss: 0.5433 - val_accuracy: 0.7370
Epoch 29/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5453 - accuracy: 0.7324 - val_loss: 0.5425 - val_accuracy: 0.7372
Epoch 30/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5451 - accuracy: 0.7328 - val_loss: 0.5436 - val_accuracy: 0.7372
Epoch 31/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5448 - accuracy: 0.7330 - val_loss: 0.5436 - val_accuracy: 0.7370
Epoch 32/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5448 - accuracy: 0.7335 - val_loss: 0.5429 - val_accuracy: 0.7352
Epoch 33/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5446 - accuracy: 0.7323 - val_loss: 0.5439 - val_accuracy: 0.7383
Epoch 34/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7323 - val_loss: 0.5416 - val_accuracy: 0.7383
Epoch 35/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5444 - accuracy: 0.7322 - val_loss: 0.5433 - val_accuracy: 0.7378
Epoch 36/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5446 - accuracy: 0.7330 - val_loss: 0.5432 - val_accuracy: 0.7378
Epoch 37/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7327 - val_loss: 0.5418 - val_accuracy: 0.7346
Epoch 38/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5444 - accuracy: 0.7332 - val_loss: 0.5439 - val_accuracy: 0.7344
Epoch 39/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5437 - accuracy: 0.7326 - val_loss: 0.5437 - val_accuracy: 0.7372
Epoch 40/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7334 - val_loss: 0.5419 - val_accuracy: 0.7367
Epoch 41/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5442 - accuracy: 0.7328 - val_loss: 0.5415 - val_accuracy: 0.7354
Epoch 42/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5438 - accuracy: 0.7336 - val_loss: 0.5415 - val_accuracy: 0.7365
Epoch 43/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5436 - accuracy: 0.7334 - val_loss: 0.5417 - val_accuracy: 0.7383
Epoch 44/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5435 - accuracy: 0.7338 - val_loss: 0.5427 - val_accuracy: 0.7383
Epoch 45/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5434 - accuracy: 0.7327 - val_loss: 0.5418 - val_accuracy: 0.7383
Epoch 46/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5431 - accuracy: 0.7335 - val_loss: 0.5423 - val_accuracy: 0.7367
Epoch 47/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5435 - accuracy: 0.7327 - val_loss: 0.5419 - val_accuracy: 0.7391
Epoch 48/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5433 - accuracy: 0.7327 - val_loss: 0.5432 - val_accuracy: 0.7385
Epoch 49/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5433 - accuracy: 0.7338 - val_loss: 0.5420 - val_accuracy: 0.7383
Epoch 50/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7331 - val_loss: 0.5420 - val_accuracy: 0.7352
Epoch 51/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7335 - val_loss: 0.5432 - val_accuracy: 0.7388
Epoch 52/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7335 - val_loss: 0.5427 - val_accuracy: 0.7331
Epoch 53/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5429 - accuracy: 0.7336 - val_loss: 0.5410 - val_accuracy: 0.7388
Epoch 54/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5431 - accuracy: 0.7331 - val_loss: 0.5415 - val_accuracy: 0.7359
Epoch 55/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5428 - accuracy: 0.7341 - val_loss: 0.5431 - val_accuracy: 0.7383
Epoch 56/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5430 - accuracy: 0.7339 - val_loss: 0.5426 - val_accuracy: 0.7388
Epoch 57/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5428 - accuracy: 0.7346 - val_loss: 0.5414 - val_accuracy: 0.7349
Epoch 58/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5426 - accuracy: 0.7340 - val_loss: 0.5417 - val_accuracy: 0.7401
Epoch 59/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5429 - accuracy: 0.7328 - val_loss: 0.5417 - val_accuracy: 0.7378
Epoch 60/100
684/684 [==============================] - 3s 5ms/step - loss: 0.5427 - accuracy: 0.7336 - val_loss: 0.5425 - val_accuracy: 0.7354
Epoch 61/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5425 - accuracy: 0.7348 - val_loss: 0.5413 - val_accuracy: 0.7380
Epoch 62/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5425 - accuracy: 0.7334 - val_loss: 0.5421 - val_accuracy: 0.7354
Epoch 63/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5425 - accuracy: 0.7341 - val_loss: 0.5418 - val_accuracy: 0.7383
Epoch 64/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5424 - accuracy: 0.7340 - val_loss: 0.5416 - val_accuracy: 0.7365
Epoch 65/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5424 - accuracy: 0.7340 - val_loss: 0.5425 - val_accuracy: 0.7388
Epoch 66/100
684/684 [==============================] - 3s 5ms/step - loss: 0.5423 - accuracy: 0.7338 - val_loss: 0.5430 - val_accuracy: 0.7391
Epoch 67/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5424 - accuracy: 0.7349 - val_loss: 0.5409 - val_accuracy: 0.7383
Epoch 68/100
684/684 [==============================] - 3s 5ms/step - loss: 0.5425 - accuracy: 0.7331 - val_loss: 0.5426 - val_accuracy: 0.7385
Epoch 69/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5423 - accuracy: 0.7337 - val_loss: 0.5429 - val_accuracy: 0.7393
Epoch 70/100
684/684 [==============================] - 3s 5ms/step - loss: 0.5427 - accuracy: 0.7331 - val_loss: 0.5420 - val_accuracy: 0.7365
Epoch 71/100
684/684 [==============================] - 3s 5ms/step - loss: 0.5420 - accuracy: 0.7340 - val_loss: 0.5442 - val_accuracy: 0.7370
Epoch 72/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5421 - accuracy: 0.7344 - val_loss: 0.5434 - val_accuracy: 0.7367
Epoch 73/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5423 - accuracy: 0.7335 - val_loss: 0.5402 - val_accuracy: 0.7380
Epoch 74/100
684/684 [==============================] - 5s 7ms/step - loss: 0.5420 - accuracy: 0.7354 - val_loss: 0.5409 - val_accuracy: 0.7383
Epoch 75/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5418 - accuracy: 0.7336 - val_loss: 0.5411 - val_accuracy: 0.7398
Epoch 76/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7330 - val_loss: 0.5405 - val_accuracy: 0.7380
Epoch 77/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7353 - val_loss: 0.5398 - val_accuracy: 0.7375
Epoch 78/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7346 - val_loss: 0.5409 - val_accuracy: 0.7391
Epoch 79/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5417 - accuracy: 0.7350 - val_loss: 0.5403 - val_accuracy: 0.7372
Epoch 80/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5416 - accuracy: 0.7353 - val_loss: 0.5403 - val_accuracy: 0.7380
Epoch 81/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5418 - accuracy: 0.7343 - val_loss: 0.5414 - val_accuracy: 0.7365
Epoch 82/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5416 - accuracy: 0.7338 - val_loss: 0.5407 - val_accuracy: 0.7365
Epoch 83/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5411 - accuracy: 0.7351 - val_loss: 0.5408 - val_accuracy: 0.7396
Epoch 84/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7335 - val_loss: 0.5411 - val_accuracy: 0.7362
Epoch 85/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5414 - accuracy: 0.7342 - val_loss: 0.5396 - val_accuracy: 0.7370
Epoch 86/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7328 - val_loss: 0.5425 - val_accuracy: 0.7367
Epoch 87/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5413 - accuracy: 0.7346 - val_loss: 0.5420 - val_accuracy: 0.7385
Epoch 88/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5417 - accuracy: 0.7342 - val_loss: 0.5421 - val_accuracy: 0.7380
Epoch 89/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7344 - val_loss: 0.5418 - val_accuracy: 0.7383
Epoch 90/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5411 - accuracy: 0.7343 - val_loss: 0.5421 - val_accuracy: 0.7380
Epoch 91/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5410 - accuracy: 0.7351 - val_loss: 0.5406 - val_accuracy: 0.7380
Epoch 92/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5410 - accuracy: 0.7342 - val_loss: 0.5421 - val_accuracy: 0.7365
Epoch 93/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5411 - accuracy: 0.7347 - val_loss: 0.5417 - val_accuracy: 0.7388
Epoch 94/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7346 - val_loss: 0.5418 - val_accuracy: 0.7380
Epoch 95/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5412 - accuracy: 0.7340 - val_loss: 0.5438 - val_accuracy: 0.7359
Epoch 96/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7340 - val_loss: 0.5426 - val_accuracy: 0.7380
Epoch 97/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5410 - accuracy: 0.7361 - val_loss: 0.5396 - val_accuracy: 0.7359
Epoch 98/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5409 - accuracy: 0.7338 - val_loss: 0.5441 - val_accuracy: 0.7349
Epoch 99/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5409 - accuracy: 0.7346 - val_loss: 0.5398 - val_accuracy: 0.7383
Epoch 100/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5410 - accuracy: 0.7350 - val_loss: 0.5429 - val_accuracy: 0.7370

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5526 - accuracy: 0.7324 - 324ms/epoch - 1ms/step
Loss: 0.552627444267273, Accuracy: 0.7323614954948425

In [ ]:
# Export model to HDF5 File

from google.colab import files

nn.save('/content/Model_1.h5')
files.download('/content/Model_1.h5')